// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elias-gamma.proto

#ifndef PROTOBUF_elias_2dgamma_2eproto__INCLUDED
#define PROTOBUF_elias_2dgamma_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_elias_2dgamma_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsPbEliasGammaSeqImpl();
void InitDefaultsPbEliasGammaSeq();
inline void InitDefaults() {
  InitDefaultsPbEliasGammaSeq();
}
}  // namespace protobuf_elias_2dgamma_2eproto
namespace skg {
namespace proto {
namespace eliasgamma {
class PbEliasGammaSeq;
class PbEliasGammaSeqDefaultTypeInternal;
extern PbEliasGammaSeqDefaultTypeInternal _PbEliasGammaSeq_default_instance_;
}  // namespace eliasgamma
}  // namespace proto
}  // namespace skg
namespace skg {
namespace proto {
namespace eliasgamma {

// ===================================================================

class PbEliasGammaSeq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:skg.proto.eliasgamma.PbEliasGammaSeq) */ {
 public:
  PbEliasGammaSeq();
  virtual ~PbEliasGammaSeq();

  PbEliasGammaSeq(const PbEliasGammaSeq& from);

  inline PbEliasGammaSeq& operator=(const PbEliasGammaSeq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PbEliasGammaSeq(PbEliasGammaSeq&& from) noexcept
    : PbEliasGammaSeq() {
    *this = ::std::move(from);
  }

  inline PbEliasGammaSeq& operator=(PbEliasGammaSeq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PbEliasGammaSeq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PbEliasGammaSeq* internal_default_instance() {
    return reinterpret_cast<const PbEliasGammaSeq*>(
               &_PbEliasGammaSeq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PbEliasGammaSeq* other);
  friend void swap(PbEliasGammaSeq& a, PbEliasGammaSeq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PbEliasGammaSeq* New() const PROTOBUF_FINAL { return New(NULL); }

  PbEliasGammaSeq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PbEliasGammaSeq& from);
  void MergeFrom(const PbEliasGammaSeq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PbEliasGammaSeq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 index_bit_idx = 4;
  int index_bit_idx_size() const;
  void clear_index_bit_idx();
  static const int kIndexBitIdxFieldNumber = 4;
  ::google::protobuf::uint64 index_bit_idx(int index) const;
  void set_index_bit_idx(int index, ::google::protobuf::uint64 value);
  void add_index_bit_idx(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      index_bit_idx() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_index_bit_idx();

  // repeated uint64 index_values = 5;
  int index_values_size() const;
  void clear_index_values();
  static const int kIndexValuesFieldNumber = 5;
  ::google::protobuf::uint64 index_values(int index) const;
  void set_index_values(int index, ::google::protobuf::uint64 value);
  void add_index_values(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      index_values() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_index_values();

  // bytes bits = 3;
  void clear_bits();
  static const int kBitsFieldNumber = 3;
  const ::std::string& bits() const;
  void set_bits(const ::std::string& value);
  #if LANG_CXX11
  void set_bits(::std::string&& value);
  #endif
  void set_bits(const char* value);
  void set_bits(const void* value, size_t size);
  ::std::string* mutable_bits();
  ::std::string* release_bits();
  void set_allocated_bits(::std::string* bits);

  // uint64 index_interval = 1;
  void clear_index_interval();
  static const int kIndexIntervalFieldNumber = 1;
  ::google::protobuf::uint64 index_interval() const;
  void set_index_interval(::google::protobuf::uint64 value);

  // uint64 length = 2;
  void clear_length();
  static const int kLengthFieldNumber = 2;
  ::google::protobuf::uint64 length() const;
  void set_length(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:skg.proto.eliasgamma.PbEliasGammaSeq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > index_bit_idx_;
  mutable int _index_bit_idx_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > index_values_;
  mutable int _index_values_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr bits_;
  ::google::protobuf::uint64 index_interval_;
  ::google::protobuf::uint64 length_;
  mutable int _cached_size_;
  friend struct ::protobuf_elias_2dgamma_2eproto::TableStruct;
  friend void ::protobuf_elias_2dgamma_2eproto::InitDefaultsPbEliasGammaSeqImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PbEliasGammaSeq

// uint64 index_interval = 1;
inline void PbEliasGammaSeq::clear_index_interval() {
  index_interval_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PbEliasGammaSeq::index_interval() const {
  // @@protoc_insertion_point(field_get:skg.proto.eliasgamma.PbEliasGammaSeq.index_interval)
  return index_interval_;
}
inline void PbEliasGammaSeq::set_index_interval(::google::protobuf::uint64 value) {
  
  index_interval_ = value;
  // @@protoc_insertion_point(field_set:skg.proto.eliasgamma.PbEliasGammaSeq.index_interval)
}

// uint64 length = 2;
inline void PbEliasGammaSeq::clear_length() {
  length_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PbEliasGammaSeq::length() const {
  // @@protoc_insertion_point(field_get:skg.proto.eliasgamma.PbEliasGammaSeq.length)
  return length_;
}
inline void PbEliasGammaSeq::set_length(::google::protobuf::uint64 value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:skg.proto.eliasgamma.PbEliasGammaSeq.length)
}

// bytes bits = 3;
inline void PbEliasGammaSeq::clear_bits() {
  bits_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PbEliasGammaSeq::bits() const {
  // @@protoc_insertion_point(field_get:skg.proto.eliasgamma.PbEliasGammaSeq.bits)
  return bits_.GetNoArena();
}
inline void PbEliasGammaSeq::set_bits(const ::std::string& value) {
  
  bits_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:skg.proto.eliasgamma.PbEliasGammaSeq.bits)
}
#if LANG_CXX11
inline void PbEliasGammaSeq::set_bits(::std::string&& value) {
  
  bits_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:skg.proto.eliasgamma.PbEliasGammaSeq.bits)
}
#endif
inline void PbEliasGammaSeq::set_bits(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  bits_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:skg.proto.eliasgamma.PbEliasGammaSeq.bits)
}
inline void PbEliasGammaSeq::set_bits(const void* value, size_t size) {
  
  bits_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:skg.proto.eliasgamma.PbEliasGammaSeq.bits)
}
inline ::std::string* PbEliasGammaSeq::mutable_bits() {
  
  // @@protoc_insertion_point(field_mutable:skg.proto.eliasgamma.PbEliasGammaSeq.bits)
  return bits_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PbEliasGammaSeq::release_bits() {
  // @@protoc_insertion_point(field_release:skg.proto.eliasgamma.PbEliasGammaSeq.bits)
  
  return bits_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PbEliasGammaSeq::set_allocated_bits(::std::string* bits) {
  if (bits != NULL) {
    
  } else {
    
  }
  bits_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bits);
  // @@protoc_insertion_point(field_set_allocated:skg.proto.eliasgamma.PbEliasGammaSeq.bits)
}

// repeated uint64 index_bit_idx = 4;
inline int PbEliasGammaSeq::index_bit_idx_size() const {
  return index_bit_idx_.size();
}
inline void PbEliasGammaSeq::clear_index_bit_idx() {
  index_bit_idx_.Clear();
}
inline ::google::protobuf::uint64 PbEliasGammaSeq::index_bit_idx(int index) const {
  // @@protoc_insertion_point(field_get:skg.proto.eliasgamma.PbEliasGammaSeq.index_bit_idx)
  return index_bit_idx_.Get(index);
}
inline void PbEliasGammaSeq::set_index_bit_idx(int index, ::google::protobuf::uint64 value) {
  index_bit_idx_.Set(index, value);
  // @@protoc_insertion_point(field_set:skg.proto.eliasgamma.PbEliasGammaSeq.index_bit_idx)
}
inline void PbEliasGammaSeq::add_index_bit_idx(::google::protobuf::uint64 value) {
  index_bit_idx_.Add(value);
  // @@protoc_insertion_point(field_add:skg.proto.eliasgamma.PbEliasGammaSeq.index_bit_idx)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
PbEliasGammaSeq::index_bit_idx() const {
  // @@protoc_insertion_point(field_list:skg.proto.eliasgamma.PbEliasGammaSeq.index_bit_idx)
  return index_bit_idx_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
PbEliasGammaSeq::mutable_index_bit_idx() {
  // @@protoc_insertion_point(field_mutable_list:skg.proto.eliasgamma.PbEliasGammaSeq.index_bit_idx)
  return &index_bit_idx_;
}

// repeated uint64 index_values = 5;
inline int PbEliasGammaSeq::index_values_size() const {
  return index_values_.size();
}
inline void PbEliasGammaSeq::clear_index_values() {
  index_values_.Clear();
}
inline ::google::protobuf::uint64 PbEliasGammaSeq::index_values(int index) const {
  // @@protoc_insertion_point(field_get:skg.proto.eliasgamma.PbEliasGammaSeq.index_values)
  return index_values_.Get(index);
}
inline void PbEliasGammaSeq::set_index_values(int index, ::google::protobuf::uint64 value) {
  index_values_.Set(index, value);
  // @@protoc_insertion_point(field_set:skg.proto.eliasgamma.PbEliasGammaSeq.index_values)
}
inline void PbEliasGammaSeq::add_index_values(::google::protobuf::uint64 value) {
  index_values_.Add(value);
  // @@protoc_insertion_point(field_add:skg.proto.eliasgamma.PbEliasGammaSeq.index_values)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
PbEliasGammaSeq::index_values() const {
  // @@protoc_insertion_point(field_list:skg.proto.eliasgamma.PbEliasGammaSeq.index_values)
  return index_values_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
PbEliasGammaSeq::mutable_index_values() {
  // @@protoc_insertion_point(field_mutable_list:skg.proto.eliasgamma.PbEliasGammaSeq.index_values)
  return &index_values_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace eliasgamma
}  // namespace proto
}  // namespace skg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_elias_2dgamma_2eproto__INCLUDED
